# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('Título', models.CharField(db_column='titulo', max_length=150, null=True)),
                ('corpo', models.TextField(db_column='corpo', null=True)),
                ('criado', models.DateTimeField(db_column='criado')),
                ('atualizado', models.DateTimeField(db_column='atualizado')),
            ],
            options={
                'db_table': 'tb_post',
            },
        ),
    ]
