# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('titulo', models.TextField(db_column='titulo')),
                ('criado', models.DateTimeField(db_column='criado')),
                ('atualizado', models.DateTimeField(db_column='atualizado')),
            ],
            options={
                'db_table': 'tb_post',
            },
        ),
    ]
