# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('campo', models.TextField(db_column='campo')),
            ],
            options={
                'db_table': 'sc_foo"."tb_foo',
            },
        ),
    ]
