# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_foo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foo',
            options={'verbose_name_plural': 'Foo'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Título',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='post',
            name='atualizado',
            field=models.DateTimeField(auto_now_add=True, db_column='atualizado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, db_column='criado'),
        ),
    ]
