# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_foo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('marca', models.TextField(db_column='marca')),
                ('modelo', models.TextField(db_column='modelo')),
            ],
            options={
                'db_table': 'sc_foo"."tb_carro',
            },
        ),
    ]
