# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='num',
            field=models.IntegerField(db_column='num', default=0),
            preserve_default=False,
        ),
    ]
