# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_foo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foo',
            new_name='Foo2',
        ),
    ]
