# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_foo_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foo',
            name='num',
        ),
    ]
