# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190219_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foo2',
            new_name='Foo',
        ),
    ]
