# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190219_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='Título',
            field=models.CharField(db_column='titulo', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='corpo',
            field=models.TextField(db_column='corpo', null=True),
        ),
    ]
